services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ultron
      - POSTGRES_USER=dani
      - POSTGRES_PASSWORD=daniadmin123
    ports:
      - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgres/data